apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "unit-test-js.fullname" . }}

spec:
  template:
    spec:
      containers:
      - name: unit-test
        image: {{.Values.job.image}}
      restartPolicy: Never
  backoffLimit: 1


